export const employees = [
  {
    firstName: 'Uche',
    lastName: 'Omodu',
    email: 'chivoomodu@gmail.com',
    role: 'Software developer',
    department: 'ICT',
    progress: '50',
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@example.com',
    role: 'Product Manager',
    department: 'Product Management',
    progress: '60',
  },
  {
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alicesmith@example.com',
    role: 'UI/UX Designer',
    department: 'Design',
    progress: '45',
  },
  {
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michaeljohnson@example.com',
    role: 'QA Engineer',
    department: 'Quality Assurance',
    progress: '70',
  },
  {
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emilybrown@example.com',
    role: 'Marketing Specialist',
    department: 'Marketing',
    progress: '55',
  },
  {
    firstName: 'David',
    lastName: 'Lee',
    email: 'davidlee@example.com',
    role: 'Data Analyst',
    department: 'Analytics',
    progress: '40',
  },
  {
    firstName: 'Sarah',
    lastName: 'Miller',
    email: 'sarahmiller@example.com',
    role: 'HR Manager',
    department: 'Human Resources',
    progress: '75',
  },
  {
    firstName: 'Robert',
    lastName: 'Taylor',
    email: 'roberttaylor@example.com',
    role: 'Sales Representative',
    department: 'Sales',
    progress: '65',
  },
  {
    firstName: 'Linda',
    lastName: 'Wilson',
    email: 'lindawilson@example.com',
    role: 'Financial Analyst',
    department: 'Finance',
    progress: '30',
  },
  {
    firstName: 'William',
    lastName: 'Anderson',
    email: 'williamanderson@example.com',
    role: 'System Administrator',
    department: 'IT',
    progress: '80',
  },
];
